# Configuración de la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/banca_db
spring.datasource.username=postgres
spring.datasource.password=Agus281119
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Desactivar el patrón Open-In-View para proteger el pool de conexiones
spring.jpa.open-in-view=false
